/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import boutiquebbdd.BoutiqueBBDD;
import static boutiquebbdd.BoutiqueBBDD.prendaJDBC;
import dao.PrendaJDBC;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_BACK_SPACE;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import modelo.Prendas;
import utilidades.EntrdaDatos;

/**
 *
 * @author usu21
 */
public class DatosPrenda extends javax.swing.JDialog {

    private Prendas nuevaPrenda;

    public Prendas getNuevaPrenda() {
        return nuevaPrenda;
    }

    public void setNuevaPrenda(Prendas nuevaPrenda) {
        this.nuevaPrenda = nuevaPrenda;
    }

//    private PrendaJDBC prendaJDBC;
    private String modo = "";
    public boolean cancelar;

    /**
     * Creates new form AltaPrenda
     */
    public DatosPrenda(java.awt.Frame parent, boolean modal, Prendas c, String modo) {
        super(parent, modal);
        cancelar = true;
        this.modo = modo;
        prendaJDBC = new PrendaJDBC();
        nuevaPrenda = c;
        initComponents();
        formulario();
        if (modo.equals("modificar")) {
            codigoTxt.setEditable(false);
            codigoTxt.setFocusable(false);
            aceptarBtn.setEnabled(true);
            this.setTitle("Modificar prenda");
        }else{
            this.setTitle("Alta prenda");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        cancelarBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        precioCosteTxt = new javax.swing.JTextField();
        colorCbo = new javax.swing.JComboBox();
        stockTxt = new javax.swing.JTextField();
        precioVentaTxt = new javax.swing.JTextField();
        precioCosteLbl = new javax.swing.JLabel();
        tallaCbo = new javax.swing.JComboBox();
        tallaLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        descripcionTxt = new javax.swing.JTextField();
        precioVentaLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        descripcionLbl = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        codigoLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta prenda");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cancelarBtnFocusGained(evt);
            }
        });
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aceptarBtnFocusGained(evt);
            }
        });
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.precioCoste}"), precioCosteTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        precioCosteTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioCosteTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioCosteTxtFocusLost(evt);
            }
        });

        colorCbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Escoge color ---", "amarillo", "azul", "blanco", "gris", "negro", "rojo", "verde" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.color}"), colorCbo, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.stock}"), stockTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        stockTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stockTxtFocusGained(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.precioVenta}"), precioVentaTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        precioVentaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioVentaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioVentaTxtFocusLost(evt);
            }
        });

        precioCosteLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioCosteLbl.setText("Precio coste:");

        tallaCbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Escoge una talla ---", "L", "M", "S", "XL", "XS" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.talla}"), tallaCbo, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        tallaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tallaLbl.setText("Talla:");

        colorLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        colorLbl.setText("Color:");

        descripcionTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.descripcion}"), descripcionTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        descripcionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionTxtFocusGained(evt);
            }
        });

        precioVentaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioVentaLbl.setText("Precio venta:");

        jLabel4.setText("€");

        stockLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stockLbl.setText("Stock:");

        jLabel9.setText("€");

        descripcionLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripcionLbl.setText("Descripcion:");

        codigoTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${nuevaPrenda.codigo}"), codigoTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        codigoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoTxtFocusLost(evt);
            }
        });
        codigoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTxtKeyTyped(evt);
            }
        });

        codigoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codigoLbl.setText("Codigo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descripcionLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tallaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCosteLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(precioVentaLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descripcionTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precioCosteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(precioVentaTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tallaCbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorCbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tallaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tallaCbo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioCosteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCosteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioVentaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stockLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cancelarBtnFocusGained
        InputMap map = new InputMap();

        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");

        cancelarBtn.setInputMap(0, map);
    }//GEN-LAST:event_cancelarBtnFocusGained
    private void formulario() {
        aceptarBtn.setEnabled(false);
        descripcionTxt.getMargin().left = 10;
        precioCosteTxt.getMargin().right = 10;
        precioVentaTxt.getMargin().right = 10;
        stockTxt.getMargin().right = 10;
        precioCosteTxt.setHorizontalAlignment(JTextField.RIGHT);
        precioVentaTxt.setHorizontalAlignment(JTextField.RIGHT);
        stockTxt.setHorizontalAlignment(JTextField.RIGHT);
        codigoTxt.setHorizontalAlignment(JTextField.CENTER);

        if (!modo.equals("modificar")) {
            codigoTxt.setText("");
            descripcionTxt.setText("");
            precioCosteTxt.setText("0");
            precioVentaTxt.setText("0");
            stockTxt.setText("0");
            colorCbo.setSelectedIndex(0);
            tallaCbo.setSelectedIndex(0);
        }
    }

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void aceptarBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aceptarBtnFocusGained
        InputMap map = new InputMap();

        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");

        aceptarBtn.setInputMap(0, map);
    }//GEN-LAST:event_aceptarBtnFocusGained

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        if (comprobarCampos()) {
            if (modo.equals("alta")) {
                if (prendaJDBC.insertarPrenda(nuevaPrenda)) {
                    JOptionPane.showMessageDialog(this, "Prenda dada de alta");
                    nuevaPrenda = new Prendas();
                    formulario();
//                dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha podido insertar la prenda", "ERROR. prenda no dada de alta", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if (prendaJDBC.modificarPrenda(nuevaPrenda)) {
                    JOptionPane.showMessageDialog(this, "Prenda modificada");
                    cancelar=false;
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha podido modificar la prenda", "ERROR. prenda no dada de alta", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private boolean comprobarCampos() {
        if (codigoTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se puede dejar el codigo vacio", "ERROR: codigo vacio", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (prendaJDBC.existePrenda(codigoTxt.getText()) && modo.equals("alta")) {
            JOptionPane.showMessageDialog(this, "Ya existe una prenda con ese codigo", "ERROR: codigo duplicado", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (descripcionTxt.getText().isEmpty() || descripcionTxt.getText().length() > 100) {
            JOptionPane.showMessageDialog(this, "Debe haber una descripcion", "ERROR: descripcion incorrecta", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (colorCbo.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un color", "ERROR: color incorrecto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tallaCbo.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una talla", "ERROR: talla incorrecta", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (nuevaPrenda.getPrecioCoste() <= 0 || nuevaPrenda.getPrecioVenta() <= 0 || nuevaPrenda.getPrecioCoste() > 999 || nuevaPrenda.getPrecioVenta() > 999) {
            JOptionPane.showMessageDialog(this, "El precio tiene que ser mayor que 0 y menor que 1000", "Precio incorrecto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (nuevaPrenda.getStock() < 0 || nuevaPrenda.getStock() != Double.parseDouble(stockTxt.getText())) {
            JOptionPane.showMessageDialog(this, "El stock tiene que ser entero y positivo", "Stock incorrecto", JOptionPane.ERROR_MESSAGE);
            stockTxt.requestFocusInWindow();
            stockTxt.selectAll();
            return false;
        }
        return true;
    }
    private void precioCosteTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCosteTxtFocusGained
        precioCosteTxt.selectAll();
    }//GEN-LAST:event_precioCosteTxtFocusGained

    private void precioCosteTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCosteTxtFocusLost
        if (nuevaPrenda.getPrecioCoste() > 0) {
            double valor = nuevaPrenda.getPrecioCoste();
            valor = (int) ((valor + 0.005) * 100);
            valor /= 100;
            precioCosteTxt.setText(Double.toString(valor));
        }
    }//GEN-LAST:event_precioCosteTxtFocusLost

    private void stockTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stockTxtFocusGained
        stockTxt.selectAll();
    }//GEN-LAST:event_stockTxtFocusGained

    private void precioVentaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioVentaTxtFocusGained
        precioVentaTxt.selectAll();
    }//GEN-LAST:event_precioVentaTxtFocusGained

    private void precioVentaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioVentaTxtFocusLost
        if (nuevaPrenda.getPrecioVenta() > 0) {
            double valor = nuevaPrenda.getPrecioVenta();
            valor = (int) ((valor + 0.005) * 100);
            valor /= 100;
            precioVentaTxt.setText(Double.toString(valor));
        }
    }//GEN-LAST:event_precioVentaTxtFocusLost

    private void codigoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTxtFocusLost
        jLabel1.setText("");
        if (prendaJDBC.existePrenda(codigoTxt.getText())) {
            JOptionPane.showMessageDialog(this, "Ya existe una prenda con ese codigo", "ERROR: codigo duplicado", JOptionPane.ERROR_MESSAGE);
            codigoTxt.requestFocusInWindow();
            codigoTxt.selectAll();
            aceptarBtn.setEnabled(false);
        } else if (!codigoTxt.getText().equals("")) {
            aceptarBtn.setEnabled(true);
        } else {
            aceptarBtn.setEnabled(false);
        }
    }//GEN-LAST:event_codigoTxtFocusLost

    private void codigoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTxtKeyTyped
        jLabel1.setText(null);
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
            if (codigoTxt.getText().length() > 7) {
                getToolkit().beep();
                evt.consume();
                jLabel1.setText("maximo 8 caracteres");
            }
        } else if (c != VK_BACK_SPACE && c != KeyEvent.VK_DELETE && c != KeyEvent.VK_ENTER) {
            getToolkit().beep();
            evt.consume();
            jLabel1.setText("Solo numeros");
        }
    }//GEN-LAST:event_codigoTxtKeyTyped

    private void descripcionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionTxtFocusGained
        descripcionTxt.selectAll();
    }//GEN-LAST:event_descripcionTxtFocusGained
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel codigoLbl;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox colorCbo;
    private javax.swing.JLabel colorLbl;
    private javax.swing.JLabel descripcionLbl;
    private javax.swing.JTextField descripcionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel precioCosteLbl;
    private javax.swing.JTextField precioCosteTxt;
    private javax.swing.JLabel precioVentaLbl;
    private javax.swing.JTextField precioVentaTxt;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JComboBox tallaCbo;
    private javax.swing.JLabel tallaLbl;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
